# Redirecionar requisições sem "www" para "www"
server {
    listen 80;
    server_name nomemagnetico.com.br;
    return 301 $scheme://www.nomemagnetico.com.br$request_uri;
}

# Servidor principal (www)
server {
    listen 80;
    server_name www.nomemagnetico.com.br;

    # Configurações de compressão para otimizar tempo de carregamento
    gzip on;
    gzip_proxied any;
    gzip_comp_level 4;
    gzip_types text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml;

    # Configuração de Proxy Reverso para o Astro (roda na porta 4321)
    location / {
        proxy_pass http://127.0.0.1:4321;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        
        # Repassa o IP real do cliente para o Astro (Útil para logs e rate limiting)
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
