name: Deploy Nome Magnético para VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependências e Build
        run: |
          npm ci
          NODE_ENV=production npm run build

      - name: Deploy para a VPS via SCP
        uses: appleboy/scp-action@master
        with:
          host: "103.199.185.152"
          username: "root"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 2222
          # Copia o conteúdo da pasta dist para a VPS
          source: "dist/*, package.json, ecosystem.config.cjs"
          target: "/var/www/webapp/nome-magnetico"
          strip_components: 1 # Remove a palavra 'dist/' na hora de colar os arquivos

      - name: Reiniciar Serviço no Servidor
        uses: appleboy/ssh-action@master
        with:
          host: "103.199.185.152"
          username: "root"
          port: 2222
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/webapp/nome-magnetico
            npm install --omit=dev
            export PORT=4321
            export NODE_ENV=production
            export HOST=0.0.0.0
            pm2 restart nomemagnetico || pm2 start dist/server/entry.mjs --name nomemagnetico
            pm2 save